export { Home } from "./Home"
export { Users } from "./users"
export { SingleUser } from "./users/[id]"
export { SingleProduct } from "./products/[id]"
export { Products } from "./products"
export { Login } from "./Login"
export { Register } from "./Register"